version: "3"
services: 
    webapi:
        build: ./app
        deploy:
            replicas: 3
        restart: always
        working_dir: /src
        volumes: 
            - ./app:/src
        ports:
            - "9000-9100:9000"
        command: sh -c "npm install && npm run start"
        networks:
            - cms_app_net
        depends_on:
            - mongo
            - redis
#            - jenkins
        links:
            - "mongo"
            - "redis"

    mongo:
        deploy:
            replicas: 3
        image: mongo:bionic
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: cms
        ports:
            - "27017-27100:27017"
        volumes:
            - ./mongo-config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - data-volume-mongoCMS:/data/db
        networks:
            - cms_app_net

    redis:
        deploy:
            replicas: 3
        image: redis:alpine
        restart: always
        networks:
            - cms_app_net

#    varnish:
#        image: varnish
#        ports:
#            - "80:80"
#        depends_on:
#            - proxyserver
#        links:
#            - proxyserver
#        volumes:
#            - ./config/default.vcl:/etc/varnish/default.vcl
#        restart: always

#    jenkins:
#        image: jenkinsci/jenkins:2.150.1-slim
#        restart: always
#        volumes: 
#            - jenkins_data:/var/jenkins_home
#        ports:
#        - "8081:8080"
#        - "50000:50000"
#        networks:
#            - cms_app_net
#        depends_on:
#            - gitrepository

#    proxyserver:
#        image: nginx:alpine
#        restart: always
#        ports:
#        - "8082:80"
#        networks:
#            - cms_app_net
#        depends_on:
#            - webapi

#    gitrepository:
#        image: 
#        networks:
#            - cms_app_net
volumes:
    data-volume-mongoCMS:
        driver: local
#    jenkins_data:
#        driver: local

networks:
    cms_app_net:
        driver: bridge