version: "3"
services: 
    webapi:
        build: ./app
        working_dir: /src
        volumes: 
            - ./app:/src
        ports:
            - "9000:9000"
        command: bash -c "npm install && npm run dev"