#
#
#       CONFIGURATRION FOR DOCKER PRODUCTION CONTAINERS
#
#

version: "3"
services: 
    webapi:
        build: ./app
        restart: always
        deploy:
            replicas: 9
            placement:
                max_replicas_per_node: 3
            restart_policy:
                condition: on-failure
        working_dir: /src
        volumes: 
            - ./app:/src
        ports:
            - "9000"
        command: sh -c "npm install --only=prod && npm run start"
        networks:
            - cms_app_net
        depends_on:
            - mongo
            - redis
        links:
            - "mongo"
            - "redis"

    mongo:
        image: mongo:bionic
        restart: always
        deploy:
            replicas: 3
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
        env_file: 
            - ./config/env/.env
        ports:
            - "27017"
        volumes:
            - ./mongo-config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - data-volume-mongoCMS:/data/db
        networks:
            - cms_app_net

    redis:
        image: redis:alpine
        restart: always
        deploy:
            replicas: 3
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
        ports:
            - "6379"
        networks:
            - cms_app_net
    
    varnish:
        image: varnish:stable
        restart: always
        deploy:
            replicas: 3
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
        depends_on:
            - proxyserver
        links:
            - proxyserver
        volumes:
            - ./config/varnish/default.vcl:/etc/varnish/default.vcl
        networks:
            - cms_app_net
        restart: always

    proxyserver:
        image: nginx:alpine
        restart: always
        deploy:
            replicas: 3
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
        ports:
            - "8080:80"
        depends_on:
            - webapi
        links:
            - webapi
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            #- ./app/public:/home/nginx/public
        networks:
            - cms_app_net

volumes:
    data-volume-mongoCMS:
        driver: local

networks:
    cms_app_net:
        driver: bridge