version: "3"
services: 
    webapi:
        container_name: myCMS.js
        build: ./app
        restart: always
        working_dir: /src
        volumes: 
            - ./app:/src
        ports:
            - "9000:9000"
        command: bash -c "npm install && npm run dev"
        networks:
            - app_net
        depends_on:
            - mongodb
            - redis
    mongodb:
        container_name: mongoCMS
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: cms
        ports:
            - "27017-27019:27017-27019"
        volumes:
            - ./mongo-config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - data-volume-mongoCMS:/data/db
        networks:
            - app_net
    redis:
        container_name: redisCMS
        image: redis
        restart: always
        networks:
            - app_net
    jenkins:
        container_name: jenkinsCMS
        image: jenkins
        restart: always
        volumes: 
            - jenkins_data:/var/jenkins_home
        ports: 
            - 8080:8080
            - 50000:50000
        networks:
            - app_net
volumes:
    data-volume-mongoCMS:
        driver: local
    jenkins_data:
        driver: local
networks:
    app_net:
        driver: bridge