const domain = (process.env.NODE_ENV_DOMAIN_NAME_SMTP) ? process.env.NODE_ENV_DOMAIN_NAME_SMTP : 'http://localhost'; 
module.exports = ({
    code,
    name,
    email,
    password
}) => {
return `
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0;">
    <meta name="format-detection" content="telephone=no"/>
    <style>
        /* Reset styles */ 
        body { margin: 0; padding: 0; min-width: 100%; width: 100% !important; height: 100% !important;}
        body, table, td, div, p, a { -webkit-font-smoothing: antialiased; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; line-height: 100%; }
        table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse !important; border-spacing: 0; }
        img { border: 0; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
        #outlook a { padding: 0; }
        .ReadMsgBody { width: 100%; } .ExternalClass { width: 100%; }
        .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; }
        /* Rounded corners for advanced mail clients only */ 
        @media all and (min-width: 560px) {
        .container { border-radius: 8px; -webkit-border-radius: 8px; -moz-border-radius: 8px; -khtml-border-radius: 8px; }
        }
        /* Set color for auto links (addresses, dates, etc.) */ 
        a, a:hover {
        color: #FFFFFF;
        }
        .footer a, .footer a:hover {
        color: #828999;
        }
    </style>
    <title>Test Email</title>
</head>
<body topmargin="0" rightmargin="0" bottommargin="0" leftmargin="0" marginwidth="0" marginheight="0" width="100%" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; width: 100%; height: 100%; -webkit-font-smoothing: antialiased; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; line-height: 100%;
    background-color: #2D3445;
    color: #FFFFFF;"
    bgcolor="#2D3445"
    text="#FFFFFF">
    <table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; width: 100%;" class="background">
        <tr>
            <td align="center" valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0;"
            bgcolor="#2D3445">
            <table border="0" cellpadding="0" cellspacing="0" align="center"
                width="500" style="border-collapse: collapse; border-spacing: 0; padding: 0; width: inherit;
                max-width: 500px;" class="wrapper">
                <tr>
                    <td align="center" valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-top: 0px;" class="hero">
                        <a target="_blank" style="text-decoration: none;" href="${domain}/">
                        <img border="0" vspace="0" hspace="0"
                        src="${domain}/mediaEmail/logoEmail.png"
                        alt="myCMS.JS Logo" title="Logo cms"
                        width="340" style="
                        width: 87.5%;
                        max-width: 340px;
                        color: #FFFFFF; font-size: 13px; margin: 0; padding: 0; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; border: none; display: block;"/>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%; font-size: 14px; font-weight: 400; line-height: 150%; letter-spacing: 2px;
                        padding-top: 27px;
                        padding-bottom: 0;
                        color: #FFFFFF;
                        font-family: sans-serif;" class="supheader">
                        REGISTRATION USER
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%; font-size: 17px; font-weight: 400; line-height: 160%;
                        padding-top: 15px; 
                        color: #FFFFFF;
                        font-family: sans-serif;" class="paragraph">
                        Welcome ${name}, to complete the admin registration just click the link below, possibly within 15 minutes, otherwise please re-register the user. Your password has been automatically generated by the system. If you want to log in, go to the user settings and run the password change.
                    </td>
                </tr>
                <tr>
                    <td valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%; font-size: 17px; font-weight: 400; line-height: 160%;
                    padding-top: 15px; 
                    color: #FFFFFF;
                    font-family: sans-serif;" class="paragraph">
                        Your data for access are:
                    </td>
                </tr>
                <tr>
                    <td valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%; font-size: 17px; font-weight: 400; line-height: 160%;
                    padding-top: 15px; 
                    color: #FFFFFF;
                    font-family: sans-serif;" class="paragraph">
                        <b>email: ${email}</b>
                    </td>
                </tr>
                <tr>
                    <td valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%; font-size: 17px; font-weight: 400; line-height: 160%;
                    padding-top: 15px; 
                    color: #FFFFFF;
                    font-family: sans-serif;" class="paragraph">
                        <b>password: ${password}</b>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%;
                        padding-top: 25px;
                        padding-bottom: 5px;" class="button">
                        <a
                        href="${domain}/api/validateRegistration/${code}" target="_blank" style="text-decoration: underline;">
                        <table border="0" cellpadding="0" cellspacing="0" align="center" style="max-width: 240px; min-width: 120px; border-collapse: collapse; border-spacing: 0; padding: 0;">
                            <tr>
                                <td align="center" valign="middle" style="padding: 12px 24px; margin: 0; text-decoration: underline; border-collapse: collapse; border-spacing: 0; border-radius: 4px; -webkit-border-radius: 4px; -moz-border-radius: 4px; -khtml-border-radius: 4px;"
                                    bgcolor="#E9703E">
                                    <a target="_blank" style="text-decoration: underline;
                                    color: #FFFFFF; font-family: sans-serif; font-size: 17px; font-weight: 400; line-height: 120%;"
                                    href="${domain}/api/validateRegistration/${code}">
                                    Confirm registration
                                    </a>
                                </td>
                            </tr>
                        </table>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="border-collapse: collapse; border-spacing: 0; margin: 0; padding: 0; padding-left: 6.25%; padding-right: 6.25%; width: 87.5%;
                        padding-top: 30px;" class="line">
                        <hr
                        color="#565F73" align="center" width="100%" size="1" noshade style="margin: 0; padding: 0;" />
                    </td>
                </tr>
            </table>
            </td>
        </tr>
    </table>
</body>
</html>
`;
};